name: Semantic release
on:
  push:
    branches:
      - main

jobs:
  # Run semantic release on main branch
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: semantic-release
          path: |
            magna/__init__.py
            CHANGELOG.md
          retention-days: 1

  # Build the Sphinx documentation
  documentation-build:
    runs-on: ubuntu-latest
    needs: ['semantic-release']
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: semantic-release

      - name: Install package requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Install Sphinx requirements
        working-directory: docs
        run: python -m pip install -r requirements.txt

      - name: Build documentation
        working-directory: docs
        run: |
          make html
          touch build/html/.nojekyll

      - uses: actions/upload-artifact@v3
        with:
          name: documentation-build
          path: docs/build/html/
          retention-days: 1

  # Update the GitHub pages branch
  documentation-deploy:
    runs-on: ubuntu-latest
    needs: ['documentation-build']
    steps:

      # Checkout the GitHub pages branch
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      # Download the documentation build
      - uses: actions/download-artifact@v3
        with:
          name: documentation-build

      # Update the GitHub pages branch
      - name: Upload documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git diff-index --quiet HEAD || git commit -m "docs update" -a
          git push
